import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  SaveAreaView: {
    flex: 1,
    backgroundColor: "white",
  },
  container: {
    backgroundColor: "white",
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    marginTop: 100,
    padding: 17,
  },
  innerContainer: {
    flex: 1,
    justifyContent: "center",
  },
  backButton: {
    position: "absolute",
    width: 48,
    height: 48,
    backgroundColor: "#F6F6F6",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    top: 50,
    left: 18,
    zIndex: 1,
  },
  title: {
    fontFamily: "Inter",
    fontSize: 32,
    fontWeight: "600",
    lineHeight: 38.73,
    letterSpacing: 0.5,
    textAlign: "left",
    marginLeft: -5,
    marginBottom: 12,
    color: "#000000",
  },
  headerContainer: {},
  header: {
    width: 100,
    height: 16,
    top: 12,
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "left",
  },
  input: {
    height: 56,
    marginBottom: 20,
    paddingHorizontal: 39,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    color: "black",
  },
  iconContainer1: {},
  icon: {
    position: "relative",
    left: 15,
    top: 39,
  },
  iconContainer2: {},
  icon2: {
    position: "relative",
    left: 15,
    top: 38,
  },
  button: {
    backgroundColor: "#8BC240",
    padding: 10,
    alignItems: "center",
    marginBottom: 12,
    minWidth: 335,
    height: 60,
    borderRadius: 40,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    top: 10,
  },
  errorText: {
    color: "red",
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "left",
    borderRadius: 5,
    marginTop: -15,
  },
  signUpText: {
    height: 35,
    textAlign: "center",
    color: "#404040",
    top: 150,
    left: 0,
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 25.6,
  },
  signUp: {
    color: "#8BC240",
    textAlign: "center",
    height: 35,
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 25.6,
  },
  rememberMeContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 20,
    right: 10,
    borderColor: "#EFEFEF",
    borderRadius: 4,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#EFEFEF",
    color: "#FFFFFF",
  },
  Remember: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 22.4,
    right: 23,
    color: "#3A3D46",
  },
  forgotPassword: {
    fontFamily: "Inter",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 22.4,
    left: 15,
    color: "#3A3D46",
  },
});

export default styles;
