import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 16,
  },
  innerContainer: {
    flex: 1,
    justifyContent: "center",
  },
  title: {
    fontFamily: "Inter",
    fontSize: 32,
    fontWeight: "600",
    lineHeight: 38.73,
    letterSpacing: 0.5,
    textAlign: "center",
    right: 100,
    top: -70,
    color: "#000000",
  },
  header: {
    width: 100,
    height: 16,
    top: -14,
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 16,
    letterSpacing: 0.5,
    textAlign: "left",
  },
  input: {
    height: 40,
    borderWidth: 1,
    marginBottom: 25,
    paddingHorizontal: 8,
    borderColor: "#EFEFEF",
  },
  button: {
    backgroundColor: "#8BC240",
    padding: 10,
    alignItems: "center",
    marginBottom: 12,
    width: 335,
    height: 60,
    borderRadius: 40,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    top: 10,
  },
  errorText: {
    color: "red",
    marginBottom: 8,
    fontSize: 14,
    fontWeight: "bold",
    textAlign: "center",
    padding: 5,
    borderRadius: 5,
  },
  signUpText: {
    width: 242,
    height: 20,
    textAlign: "center",
    color: "black",
    top: 170,
    left: 30,
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 25.6,
  },
  signUp: {
    color: "#8BC240",
    textAlign: "center",
    height: 30,
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 25.6,
  },
});

export default styles;
