import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    paddingHorizontal: 10,
    top: -5,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logo: {
    flexDirection: "row",
    width: 252,
    height: 95,
    left: -35,
    top: -5,
  },
  gradient: {
    height: 150,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
  },
  icon: {
    flexDirection: "row",
    width: 51,
    height: 51,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#92929233",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  searchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },

  searchInput: {
    width: 269,
    height: 55,
    backgroundColor: "#fff",
    borderRadius: 39,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#92929233",
    paddingLeft: 45,
  },

  searchIcon: {
    position: "absolute",
    left: 16,
    top: "45%",
    transform: [{ translateY: -14 }],
    width: 24,
    height: 24,
  },
  barIcon: {
    flexDirection: "row",
    left: 290,
    marginTop: -70,
    marginBottom: 16,
    width: 51,
    height: 51,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#92929233",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  barIcon2: {
    alignItems: "center",
    width: 24,
    height: 24,
  },
  filters: {
    width: 350,
    height: 48,
    flexDirection: "row",
    marginBottom: 16,
    justifyContent: "center",
    gap: 8,
  },
  filterButton: {
    width: 106,
    height: 48,
    padding: 14,
    paddingHorizontal: 24,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#ccc",
    marginRight: 8,
  },
  filterButtonActive: {
    width: 100,
    height: 48,
    padding: 14,
    paddingHorizontal: 24,
    borderRadius: 100,
    backgroundColor: "#8BC240",
    marginRight: 8,
  },
  filterText: {
    color: "#555",
    width: 67,
    height: 20,
  },
  filterTextActive: {
    color: "#fff",
    textAlign: "center",
    alignContent: "center",
    justifyContent: "center",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 4,
  },
  sectionTitle: {
    fontFamily: "Inter",
    fontSize: 20,
    fontWeight: "600",
    lineHeight: 24.2,
    textDecorationLine: "none",
    textDecorationStyle: "solid",
    left: 16,
  },
  viewAll: {
    fontFamily: "Inter",
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 18.6,
    textDecorationLine: "none",
    textDecorationStyle: "solid",
    color: "#818181",
    right: 16,
  },
});
export default styles;
