import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "flex-start",
    backgroundColor: "#f5f5f5",
  },
  gradient: {
    height: 305,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
  },
  text: {
    color: "#000000",
    paddingHorizontal: 30,
    paddingTop: 55,
    fontFamily: "Inter_700Bold",
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 31.47,
    textAlign: "left",
  },
  ImageContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 131,
    marginTop: 30,
    gap: 15,
  },
  Ai: {
    alignItems: "center",
    justifyContent: "center",
    width: 83,
    height: 31,
  },
  AiText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 19.36,
    color: "#000000",
  },
  ProfileContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 50,
    gap: 15,
    paddingHorizontal: 30,
  },

  ProfileItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 15,
    width: "100%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#92929233",
    borderRadius: 14,
    height: 60,
    paddingHorizontal: 20,
  },
  ProfileItemText: {
    fontFamily: "Inter_400Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 20,
    color: "#000000",
  },
  ProfileItemIcon: {
    width: 24,
    height: 24,
  },

  ProfileItemIconLogout: {
    width: 24,
    height: 24,
    marginLeft: 5,
  },
  ProfileItemTextLogout: {
    fontFamily: "Poppins",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 20,
    color: "#FF2650",
  },

  ProfileArrow: {
    color: "#2F2D3D",
    width: 9,
    height: 15,
    marginLeft: 12,
    justifyContent: "flex-end",
  },
  PrivacyContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 70,
  },
  Privacy: {
    fontFamily: "Inter_400Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 17.44,
    color: "#8BC240",
    textDecorationLine: "underline",
    textDecorationStyle: "solid",
  },
  VersionContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 40,
  },
  VersionText: {
    fontFamily: "Poppins",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 17.4,
    color: "#1D1D1C",
  },
});
