import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    opacity: 1,
    position: "relative",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  propertyImage: {
    height: 350,
    resizeMode: "cover",
  },

  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    position: "absolute",
    bottom: 50,
    width: "100%",
  },
  gradientDot: {
    width: 20,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: "#8BC240",
  },
  inactiveDot: {
    width: 20,
    height: 5,
    borderRadius: 4,
    backgroundColor: "#ccc",
    marginHorizontal: 5,
  },
  icons: {
    position: "absolute",
    justifyContent: "space-between",
    flexDirection: "row",
    width: "100%",
    top: 45,
    paddingHorizontal: 16,
  },
  icon1: {
    backgroundColor: "white",
    borderRadius: 50,
    padding: 8,
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  icon2: {
    backgroundColor: "white",
    borderRadius: 50,
    padding: 8,
  },
  detailsCard: {
    padding: 16,
    marginVertical: 8,
    borderRadius: 8,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    marginTop: -35,
    backgroundColor: "white",
  },
  priceSection: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginBottom: 12,
    top: 5,
  },
  price: {
    fontFamily: "PoppinsSemiBold",
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 36,
    color: "#8BC240",
  },
  shares: {
    fontSize: 14,
    color: "#464851",
    marginLeft: 20,
    fontFamily: "InterMedium",
    fontWeight: "500",
  },
  title: {
    fontSize: 20,
    fontWeight: "semibold",
    marginBottom: 10,
    fontFamily: "PoppinsSemiBold",
    color: "#2B2B2B",
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 13,
  },

  location: {
    color: "#666",
    fontFamily: "PoppinsRegular",
    fontSize: 13.3,
    fontWeight: "400",
    lineHeight: 22,
    textAlign: "left",
  },
  features: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },

  featureText: {
    marginLeft: 4,
    fontSize: 11,
    color: "#818181",
    fontFamily: "InterMedium",
    fontWeight: "500",
  },
  badge: {
    height: 36,
    backgroundColor: "transparent",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    borderWidth: 1,
    borderColor: "#8BC240",
    borderRadius: 50,
    marginVertical: 8,
    flexDirection: "row",
    paddingHorizontal: 12,
    gap: 4,
  },

  badgeText: {
    justifyContent: "center",
    alignItems: "center",
    color: "#14161C",
    fontSize: 15,
    fontWeight: "500",
    fontFamily: "InterMedium",
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: "semibold",
    marginVertical: 8,
    fontFamily: "InterSemiBold",
    color: "black",
  },
  description: {
    fontSize: 16,
    color: "#464851",
    fontWeight: "400",
    fontFamily: "InterRegular",
    textAlign: "justify",
    width: "96%",
  },

  amenitiesFeatures: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: 20,
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    flexWrap: "wrap",
    gap: 16,
  },
  amenitiesItem: {
    flexDirection: "column",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    width: "20%",
    position: "relative",
  },
  icon: {
    backgroundColor: "#F6F6F6",
    width: 49,
    height: 50,
    borderRadius: 25,
    padding: 14,
  },
  amenitiesFeatureNum: {
    backgroundColor: "#8BC240",
    borderRadius: 100,
    color: "white",
    width: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 11.88,
    position: "absolute",
    fontWeight: "600",
    fontFamily: "PlusJakartaSansSemiBold",
    bottom: 15,
  },
  amenitiesFeatureText: {
    fontFamily: "PlusJakartaSansMedium",
    fontSize: 11.88,
    fontWeight: "500",
    lineHeight: 14.97,
    color: "#818181",
    marginTop: 3,
    justifyContent: "center",
    textAlign: "center",
  },
  contactCard: {
    width: "100%",
    height: 178,
    borderColor: "#EBEBEB",
    borderWidth: 1,
    borderRadius: 33,
    padding: 16,
    backgroundColor: "#fff",

    elevation: 2,
  },
  contactTitle: {
    fontFamily: "InterMedium",
    color: "#14161C",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "left",
    marginBottom: 10,
  },
  whatsappIcon: {
    width: 39,
    height: 40,

    top: -40,
    position: "absolute",
  },
  contactDescription: {
    fontFamily: "InterRegular",
    fontSize: 14,
    fontWeight: "400",
    textAlign: "left",
    width: "90%",
    marginBottom: 16,
    color: "#14161C",
  },
  personContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  person: {
    width: 60,
    height: 60,
    borderRadius: 50,
  },
  whatsappButtonText: {
    color: "#14161C",
    fontSize: 16,
    fontWeight: "medium",
    marginLeft: 4,
    fontFamily: "InterMedium",
  },
  priceCard: {
    width: "100%",
    maxHeight: 330,
    padding: 16,
    marginVertical: 6,
    borderRadius: 33,

    backgroundColor: "#8BC240",
  },
  pricecontent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 0,
  },
  priceTitle: {
    color: "white",
    fontFamily: "InterRegular",
    fontSize: 28,
    fontWeight: "500",
    lineHeight: 60,
    letterSpacing: -0.48,
    textAlign: "left",
  },
  whiteBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    height: 14,
    width: 300,
    backgroundColor: "#FFFFFF99",
    marginVertical: 10,
    borderRadius: 20,
    top: -10,
  },
  whiteCircle: {
    backgroundColor: "white",
    width: 14,
    height: 14,
    borderRadius: 20,
  },
  Cashtitle: {
    fontFamily: "InterMedium",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 28,
    letterSpacing: -0.48,
    textAlign: "left",
    color: "white",
    top: 12,
  },
  priceSubtitle: {
    fontSize: 14,
    color: "white",

    fontFamily: "InterMedium",
    fontWeight: "500",
  },
  priceDetails: {
    fontFamily: "InterMedium",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 25,
    letterSpacing: -0.48,
    color: "white",
    marginBottom: 8,
  },
  priceInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  cashPriceTitle: {
    fontFamily: "InterMedium",
    fontWeight: "500",
    fontSize: 14,
    color: "white",
    marginTop: 15,
  },
  cashPriceInfo: {
    fontFamily: "InterSemiBold",
    fontWeight: "600",
    fontSize: 22,
    color: "white",
    marginBottom: 10,
  },
  priceLabel: {
    fontFamily: "InterMedium",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: -0.48,
    textAlign: "left",
    color: "white",
  },
  priceValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "white",
  },
  card1: {
    width: 334,
    height: 112,
    left: 15,
    backgroundColor: "#8BC240",
    borderRadius: 24,
    padding: 16,
    marginBottom: 150,
  },
  card: {
    width: "100%",
    height: 208,

    backgroundColor: "#8BC240",
    borderRadius: 24,
    padding: 16,
    marginBottom: 100,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "white",
    marginBottom: 8,
    fontFamily: "InterMedium",
  },
  fromToText: {
    fontSize: 24,
    fontWeight: "500",
    color: "white",
    marginBottom: 8,
    fontFamily: "InterMedium",
  },
  bar: {
    width: 283,
    height: 1,
    backgroundColor: "white",
    marginVertical: 15,
  },
  largeText: {
    fontSize: 18,
    left: 5,
    fontWeight: "semibold",
    color: "#fff",
    fontFamily: "InterSemiBold",
  },
  descriptionWebView: {
    width: "100%",
    backgroundColor: "transparent",
  },
  tabContainer: {
    backgroundColor: "transparent",
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    borderRadius: 20,
  },
  buttonGreen: {
    backgroundColor: "#8BC240",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 30,
    marginBottom: 10,
    width: "100%",
    alignItems: "center",
  },
  buttonDark: {
    backgroundColor: "#061C27",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 30,
    width: "100%",
    alignItems: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "interMedium",
  },
  soldOutLabel: {
    position: "relative",

    fontSize: 14,
    color: "white",
    fontWeight: "medium",
    fontFamily: "InterMedium",
  },
});

export default styles;
