import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "white",
    opacity: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  propertyImage: {
    height: 350,
    resizeMode: "cover",
  },

  paginationContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
    position: "absolute",
    top: 270,
    left: 120,
  },
  gradientDot: {
    width: 20,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: "#8BC240",
  },
  inactiveDot: {
    width: 20,
    height: 5,
    borderRadius: 4,
    backgroundColor: "#ccc",
    marginHorizontal: 5,
  },
  icons: {
    position: "absolute",
    justifyContent: "center",
    flexDirection: "row",
    top: 38,
  },
  icon1: {
    backgroundColor: "white",
    borderRadius: 50,
    padding: 8,
    height: 40,
    width: 40,
    justifyContent: "center",
    alignItems: "center",
    left: 20,
  },
  icon2: {
    backgroundColor: "white",
    borderRadius: 50,
    padding: 8,
    left: 290,
  },
  detailsCard: {
    padding: 16,
    marginVertical: 8,
    borderRadius: 8,
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    marginTop: -35,
    backgroundColor: "white",
  },
  priceSection: {
    width: "60%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
    top: 5,
  },
  price: {
    fontFamily: "Poppins",
    fontSize: 24,
    fontWeight: "600",
    lineHeight: 36,
    color: "#8BC240",
  },
  shares: {
    fontSize: 14,
    color: "#464851",
    marginLeft: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 13,
  },
  locationicon: {
    width: 20,
    height: 20,
  },
  location: {
    color: "#666",
    fontFamily: "Poppins",
    fontSize: 13.3,
    fontWeight: "400",
    lineHeight: 22,
    textAlign: "left",
  },
  features: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  featureItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 22,
  },
  featureIcon: {
    width: "80%",
    height: "80%",
  },
  featureText: {
    marginLeft: 4,
    fontSize: 12,
    color: "#818181",
  },
  badge: {
    width: 88,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 1.84,
    padding: 15,
    borderWidth: 1,
    borderColor: "#8BC240",
    borderRadius: 50,
    marginVertical: 8,
  },
  badgeText: {
    width: 88,
    justifyContent: "center",
    alignItems: "center",
    color: "#14161C",
    fontSize: 15,
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginVertical: 8,
  },
  description: {
    fontSize: 16,
    color: "#464851",
    fontWeight: "400",
  },
  amenitiesFeatures: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    marginTop: 20,
    gap: 20,
    justifyContent: "center",
    right: 15,
  },
  amenitiesItem: {
    flexDirection: "column",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    marginBottom: 16,
    height: 45,
    bottom: -13,
  },
  icon: {
    backgroundColor: "#F6F6F6",
    width: 49,
    height: 45,
    borderRadius: 25,
    marginTop: 5,
    padding: 14,
  },
  amenitiesFeatureNum: {
    backgroundColor: "#8BC240",
    borderRadius: 8,
    color: "white",
    width: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 12,
  },
  amenitiesFeatureText: {
    fontFamily: "Plus Jakarta Sans",
    fontSize: 11.88,
    fontWeight: "500",
    lineHeight: 14.97,
    color: "#818181",
    marginTop: 5,
    justifyContent: "center",
    textAlign: "center",
  },
  contactCard: {
    width: "100%",
    height: 178,
    borderColor: "#EBEBEB",
    borderWidth: 1,
    borderRadius: 33,
    padding: 16,
    backgroundColor: "#fff",
    marginVertical: 8,
    elevation: 2,
  },
  contactTitle: {
    fontFamily: "Inter",
    fontSize: 16,
    fontWeight: "500",
    textAlign: "left",
    marginBottom: 12,
  },
  whatsappIcon: {
    width: 39,
    height: 40,
    right: 0,
    top: -40,
    position: "absolute",
  },
  contactDescription: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "400",
    textAlign: "left",
    width: "90%",
    marginBottom: 16,
  },
  personContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
  },
  person: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 10,
  },
  whatsappButtonText: {
    color: "#14161C",
    fontSize: 16,
    fontWeight: "medium",
    marginLeft: 8,
  },
  priceCard: {
    width: "100%",
    maxHeight: 330,
    padding: 16,
    marginVertical: 6,
    borderRadius: 33,

    backgroundColor: "#8BC240",
  },
  pricecontent: {
    flexDirection: "row",

    alignItems: "center",
    marginBottom: 16,
  },
  priceTitle: {
    color: "white",
    fontFamily: "Inter",
    fontSize: 28,
    fontWeight: "500",
    lineHeight: 60,
    letterSpacing: -0.48,
    textAlign: "left",
  },
  whiteBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    height: 14,
    width: 300,
    backgroundColor: "#FFFFFF99",
    marginVertical: 10,
    borderRadius: 20,
    top: -10,
  },
  whiteCircle: {
    backgroundColor: "white",
    width: 14,
    height: 14,
    borderRadius: 20,
  },
  Cashtitle: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 28,
    letterSpacing: -0.48,
    textAlign: "left",
    color: "white",
    top: 12,
  },
  priceSubtitle: {
    left: 65,
    fontSize: 14,
    color: "white",
    marginVertical: 4,
  },
  priceDetails: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 25,
    letterSpacing: -0.48,
    color: "white",
    marginBottom: 8,
    top: -10,
  },
  priceInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 4,
    top: -10,
  },
  priceLabel: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: -0.48,
    textAlign: "left",
    color: "white",
  },
  priceValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "white",
  },
  card1: {
    width: 334,
    height: 112,
    left: 15,
    backgroundColor: "#8BC240",
    borderRadius: 24,
    padding: 16,
    marginBottom: 100,
  },
  card: {
    width: "100%",
    height: 208,

    backgroundColor: "#8BC240",
    borderRadius: 24,
    padding: 16,
    marginBottom: 100,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "white",
    marginBottom: 8,
  },
  bar: {
    width: 283,
    height: 1,
    backgroundColor: "white",
    marginVertical: 15,
  },
  largeText: {
    fontSize: 20,
    left: 5,
    fontWeight: "bold",
    color: "#fff",
  },
});

export default styles;
