import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    top: -50,
  },
  slideContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },

  phoneContainer: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  screenContainer: {
    position: 'absolute',

    borderRadius: 50,
    overflow: 'hidden',
  },
  gradientOverlay: {
    position: 'absolute',
    width: '100%',
    height: '20%',
    zIndex: 1,
  },
  gradient: {
    flex: 1,
  },
  header: {
    marginBottom: 30,
    top: 20,
    textAlign: 'center',
    fontFamily: 'Inter_600SemiBold',
    fontSize: 24,
    fontWeight: '600',
    color: '#0E0C20',
    marginTop: 10,
    zIndex: 1000,
  },
  description: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 25,
    textAlign: 'center',
    color: '#242B36',
    top: 3,
  },
  gradientDot: {
    width: 20,
    height: 4,
    borderRadius: 5,
    marginHorizontal: 5,
    right: 10,
    top: -85,
  },
  inactiveDot: {
    width: 20,
    height: 5,
    borderRadius: 4,
    backgroundColor: '#C9C9C9',
    marginHorizontal: 5,
    top: -85,
    right: 10,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  iconsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    position: 'absolute',
    top: 150,
  },
  iconItem1: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    width: 141,
    height: 52,
    backgroundColor: 'white',
    borderRadius: 10,
    gap: 10,
    right: 20,
    top: 50,
    shadowColor: '#0E0E0E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 1,
    elevation: 1,
    paddingLeft: 5,
  },
  iconItem2: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    width: 150,
    height: 52,
    backgroundColor: 'white',
    borderRadius: 10,
    gap: 10,
    left: 45,
    top: 125,
    shadowColor: '#0E0E0E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 1,
    elevation: 1,
    paddingLeft: 5,
  },
  iconItem3: {
    position: 'absolute',
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    width: 162,
    height: 52,
    backgroundColor: 'white',
    borderRadius: 10,
    gap: 12,
    top: 255,
    left: -82,
    zIndex: 100,
    shadowColor: '#0E0E0E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 1,
    elevation: 1,
    paddingLeft: 5,
  },
  Bedroom: {
    left: 4,
  },
  Bathroom: {
    left: 4,
  },
  Parking: {
    left: 5,
  },
  iconLabel: {
    fontFamily: 'Inter_400Regular',
    fontSize: 14,
    fontWeight: '400',
    color: '#242B36',
    alignItems: 'center',
    zIndex: 100,
  },
});
